### ISSUE TITLE
Apparently not working with glslify 6.1.0 (current)

### ISSUE THREAD

**Issue by taseenb** [hughsk/glslify-import#6]
Imports fail in with the latest glslify 6.1.0 .
I tried to run the tests with 6.1.0, and they fail. It seems that existing tests used to run with glslify 2.1.2.

Any hope you could check that...? In any case, opportunity to thank you for the great stuff that you share :)

**Comment by mwmwmw** [comment]
Same here. There error I'm getting is
```
  if (!total) return done(null, src)
                     ^

TypeError: done is not a function
    at glslifyImport (\node_modules\glslify-import\index.js:53:22)
    at nr (\node_modules\module-deps\index.js:301:23)
    at onfile (\node_modules\resolve\lib\async.js:56:21)
    at onex (\node_modules\resolve\lib\async.js:104:32)
    at \node_modules\resolve\lib\async.js:24:24
    at FSReqWrap.oncomplete (fs.js:153:5)
```

I'm guessing it's an API change
